### ISSUE TITLE
What does setting CreateContainerIfNotExists do?

### ISSUE THREAD

**Issue by lol768** [managedcode/Storage#91] opened 2024-05-27 14:31 UTC
I don't want this library to try and create buckets. I know the bucket exists.

My IAM user doesn't have permission to create buckets, so it's never going to get a HTTP 409 back from GCP.

**Comment by KSemenenko** [comment] 2024-05-27 15:20
this is good point!

**Comment by hoylu-royberg** [comment] 2024-05-30 04:13
I also discovered that `CreateContainerIfNotExists` does nothing in the latest release (2.1.14), so I'm very happy to hear that a fix might come soon for this 🙏

**Comment by KSemenenko** [comment] 2024-06-02 21:31
plese check version '2.1.16'

**Comment by KSemenenko** [comment] 2024-06-13 18:07
Is this fixed?

**Comment by hoylu-royberg** [comment] 2024-06-13 23:01
> Is this fixed?

Almost. Most of the issues I saw before are now handled correctly. However, for Azure there is still an issue, and today I finally had time to debug what the issue is; I think the problem is that in `AzureStorage.CreateContainerInternalAsync` it does this if `CreateContainerIfNotExists` is `false`:
https://github.com/managedcode/Storage/blob/eb9a11335786ac030b468fbf4426f0252821e82c/ManagedCode.Storage.Azure/AzureStorage.cs#L152

We use very restrictive Azure blob storage container settings for our production containers, so an underlying call to `GetPropertiesAsync` fails.  The result is that an `Azure.RequestFailedException` is thrown, and as a result `IsContainerCreated` will be set to false, and you will get an ugly XML formatted log messages like this one from the Azure client library:
```
Azure.RequestFailedException: This request is not authorized to perform this operation.
RequestId:6b175b0f-301e-002f-25de-bde1bf000000
Time:2024-06-13T22:12:52.6303820Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:6b175b0f-301e-002f-25de-bde1bf000000
Time:2024-06-13T22:12:52.6303820Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 6b175b0f-301e-002f-25de-bde1bf000000
x-ms-client-request-id: b5e7b4cc-2a8d-49d8-8daf-317faa19bd53
x-ms-version: 2024-05-04
x-ms-error-code: AuthorizationFailure
Date: Thu, 13 Jun 2024 22:12:52 GMT
Content-Length: 246
Content-Type: application/xml

   at Azure.Storage.Blobs.ContainerRestClient.GetPropertiesAsync(Nullable`1 timeout, String leaseId, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.ExistsInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.ExistsAsync(CancellationToken cancellationToken)
   at ManagedCode.Storage.Azure.AzureStorage.CreateContainerInternalAsync(CancellationToken cancellationToken) in /_/Storages/ManagedCode.Storage.Azure/AzureStorage.cs:line 157
```
While everything seems to work fine on the surface, this issue slows down all blob storage operations, and pollutes our logs with the above error level messages, when using Azure as the blob storage provider.

So I think it perhaps would be better to always set `IsContainerCreated` to `true` in all the cloud storage provider specific `CreateContainerInternalAsync` implementations  if `CreateContainerIfNotExists` has been set to `false`. And for that scenario, just leave it to the ManagedCode.Storage library consumer to make sure that the bucket/container exists already.

**Comment by KSemenenko** [comment] 2024-06-14 09:17
can you check new version please? 
```
          try
          {
              IsContainerCreated = await StorageClient.ExistsAsync(cancellationToken);
          }
          catch (RequestFailedException e)
          {
              logger.LogException(e);
              //probably we don't have permission to check if container exists
              IsContainerCreated = true;
          }
```

**Comment by hoylu-royberg** [comment] 2024-06-14 23:12
With version 2.1.19 we only get the ugly log statement once per session, so that is acceptable. Thank you! 🙂
I'll leave it to you or issue creator (@lol768) to close this issue.

**Comment by KSemenenko** [comment] 2024-07-13 14:22
https://github.com/managedcode/Storage/releases/tag/2.1.20

**Closed by KSemenenko** 2024-07-13 14:22 UTC

**Comment by KSemenenko** [comment] 2024-07-15 18:58
> Is there supposed to be a 2.1.20 of the Gcp provider?
Yes, please let me know how it works for you

**Comment by lol768** [comment] 2024-07-15 19:08
Sorry, where is it? https://www.nuget.org/packages/ManagedCode.Storage.Gcp#versions-body-tab

**Comment by KSemenenko** [comment] 2024-07-16 18:08
https://www.nuget.org/packages/ManagedCode.Storage.Google

**Comment by KSemenenko** [comment] 2024-07-16 18:12
Impish gcp package, it was prone ably autorenameing
